on:
  push:
    tags:
    - '*'
jobs:
  build-and-publish:
    runs-on: 'ubuntu-latest'
    env:
      GH_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
    steps:
    - uses: 'actions/checkout@v4'
    - run: 'make'
    - run: 'gh release create ${{ github.ref_name }} a.out'
